SELECT * FROM ALUNOS

INSERT ALUNOS (MATRICULA, NOME, CODESTCIVIL, DTNASC, HRNASC)
VALUES (1,'JOEL 2','S','01/01/1991','12:00')

ALTER TABLE ALUNOS ADD CODESTCIVIL CHAR(1)
UPDATE ALUNOS SET CODESTCIVIL = 'C'
WHERE MATRICULA = 2
--CRIAR UMA TABELA COM OS ESTADOS CIVIS POSSÍVEIS
--CRIAR UM RELACIONAMENTO
GO
ALTER TABLE ALUNOS 
ADD CONSTRAINT FK_ALUNOS_EST_CIVIL 
FOREIGN KEY (CODESTCIVIL) 
REFERENCES ESTADOCIVIL (CODESTCIVIL)


CREATE TABLE ESTADOCIVIL
(
    CODESTCIVIL CHAR(1)
        CONSTRAINT PK_ESTADOCIVIL
        PRIMARY KEY,
    DESCESTCIVIL CHAR(50) 
)
GO
INSERT ESTADOCIVIL (CODESTCIVIL, DESCESTCIVIL)
VALUES ('C','CASADO')

INSERT ESTADOCIVIL (CODESTCIVIL, DESCESTCIVIL)
VALUES ('S','SOLTEIRO')

INSERT ESTADOCIVIL (CODESTCIVIL, DESCESTCIVIL)
VALUES ('D','DIVORCIADO')

INSERT ESTADOCIVIL (CODESTCIVIL, DESCESTCIVIL)
VALUES ('D','DISQUITADO')


SELECT * FROM ESTADOCIVIL