CREATE DATABASE UNIVILLE
GO
USE UNIVILLE
GO
CREATE TABLE ALUNOS
(
    MATRICULA INT IDENTITY (1,1)
        CONSTRAINT PK_ALUNO PRIMARY KEY,
    NOME CHAR(50),
    ESTADO CHAR(2),
    DTNASC DATE,
    HRNASC TIME,
    SALARIO MONEY,
    RENDA DECIMAL(10,2),
    ALTURA FLOAT
)
GO
INSERT ALUNOS (NOME, ESTADO, DTNASC, HRNASC)
VALUES ('JOEL','AM','01/01/1991','12:00')

SELECT * FROM ALUNOS

UPDATE ALUNOS SET SALARIO = 20000
WHERE MATRICULA = 2

DELETE FROM ALUNOS WHERE MATRICULA = 1