--CREATE
CREATE TABLE ALUNOS
(
    MATRICULA INT IDENTITY (1,1)
     CONSTRAINT PK_ALUNO PRIMARY KEY,
    NOME CHAR(50),
    ESTADO CHAR(2)
)
SELECT * FROM ALUNOS
UPDATE ALUNOS SET NOME = 'DORNELA'
WHERE MATRICULA = 1

INSERT ALUNOS (NOME, ESTADO) VALUES ('LUISA2','PR')

--CONSTRAINT

--ALTER TABLE

ALTER TABLE ALUNOS ADD DTNASC DATE NOT NULL 
DEFAULT GETDATE()

--INSERT

--SELECT

CREATE TABLE ESTADOS
(
    SIGLA CHAR(2) CONSTRAINT PK_ESTADO PRIMARY KEY,
    NOMEESTADO CHAR(50)
)

INSERT ESTADOS (SIGLA,NOMEESTADO)
VALUES ('PR', 'PARANÁ')

ALTER TABLE ALUNOS ADD CONSTRAINT FK_ALUNOS_ESTADO
FOREIGN KEY (ESTADO) REFERENCES ESTADOS(SIGLA)